name: BackendCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        working-directory: "BMTH Application (back end)"
        run: dotnet restore "BMTH Application (back end).sln"

      - name: Build
        working-directory: "BMTH Application (back end)"
        run: dotnet build "Test.Unit/Test.Unit.csproj" --no-restore --configuration Release

      - name: Run tests
        working-directory: "BMTH Application (back end)"
        run: dotnet test "Test.Unit/Test.Unit.csproj" --no-build --configuration Release